name: Run tests and send coverage report to codecov

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install requirements
        run: npm install

      - name: Install test and coverage framework
        run: npm install --save-dev mocha c8

      - name: Run tests
        run: npm run coverage

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Manuel-Materazzo/Fluid-Proxy

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Manuel-Materazzo/Fluid-Proxy